USE Synthite_Canteen
GO
TRUNCATE TABLE Canteen_Menu
TRUNCATE TABLE Canteen_Expense
TRUNCATE TABLE Canteen_Menu_Mapping
TRUNCATE TABLE Canteen_Transaction
TRUNCATE TABLE Company
TRUNCATE TABLE Department
TRUNCATE TABLE Employee
TRUNCATE TABLE Payment_Mode
TRUNCATE TABLE Revision
TRUNCATE TABLE Revision_Details
TRUNCATE TABLE Temp_Report
TRUNCATE TABLE [User]
TRUNCATE TABLE User_Login
